### ISSUE TITLE
More secure checksums

### ISSUE THREAD

**Issue by PanisSupraOmnia** [Jguer/yay-PKGBUILD#1]
Would it be possible to use SHA512, or at least SHA256 for the checksums in the yay PKGBUILDs? Thanks.

**Comment by Jguer** [comment]
Sure thing, something SHA2 it is

**Comment by PanisSupraOmnia** [comment]
Fixed in f218078a41253691ac8a852698872b51859c0333.

**Comment by Jguer** [comment]
I remembered :slightly_smiling_face:
